services:
  - type: web
    name: my-python-service
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free

build:
    python:
        version: 3.9

env:
    FLASK_APP: app.py
    PORT: 5000

run:
    command: python app.py